name: Bump version number
on:
  workflow_dispatch:
    inputs:
      version_part:
        type: choice
        description: Part of version number to bump
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      version_number: ${{steps.new_version_number.outputs.version_number}}
    steps:
      # Checkout repository, bump version with ./version.sh, and commit
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.NANOME_BOT_PAT }}
      - name: git setup
        run: |
          git config --global user.name 'nanome-bot'
          git config --global user.email '45469149+nanome-bot@users.noreply.github.com'
      - name: Run version.sh
        run: |
          pip install bump2version
          chmod +x ./version.sh
          ./version.sh ${{ github.event.inputs.version_part }}
      - name: get new version number
        id: new_version_number
        run: |
          new_ver=$(cat setup.cfg | grep current_version | awk -F "=" '{print $2}' | xargs)
          echo "::set-output name=version_number::$(echo $new_ver)"
      - name: Push to GitHub
        run: |
          git push --follow-tags
  set-version-number-env:
    runs-on: ubuntu-latest
    needs: "bump-version"
    steps:
      - run: |
          VERSION_NUMBER=${{needs.bump-version.outputs.version_number}}
          if [ -z "$VERSION_NUMBER" ]; then
            echo "::error::No version number found"
            exit 1
          fi
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV

  push-to-registry:
    needs: [bump-version, set-version-number-env]
    uses: ./.github/workflows/push-to-registry.yml
    with:
      tag: $VERSION_NUMBER
    secrets: inherit
