name: Bump version number
on:
  workflow_dispatch:
    inputs:
      version_part:
        type: choice
        description: Part of version number to bump
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      version_number: ${{steps.new_version_number.outputs.version_number}}
    steps:
      # Checkout repository, bump version with ./version.sh, and commit
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.NANOME_BOT_PAT }}
      - name: git setup
        run: |
          git config --global user.name 'nanome-bot'
          git config --global user.email '45469149+nanome-bot@users.noreply.github.com'
      - name: Run version.sh
        run: |
          pip install bump2version
          chmod +x ./version.sh
          ./version.sh ${{ github.event.inputs.version_part }}
      - name: get new version number
        id: new_version_number
        run: |
          new_ver=$(cat setup.cfg | grep current_version | awk -F "=" '{print $2}' | xargs)
          echo "::set-output name=version_number::$(echo $new_ver)"
      - name: Push to GitHub
        run: |
          git push --follow-tags
  validate-bump-version-output:
    runs-on: ubuntu-latest
    needs: "bump-version"
    steps:
      - run: |
          new_ver=${{needs.bump-version.outputs.version_number}}
          if [ -z "$new_ver" ]; then
            echo "::error::No version number found"
            exit 1
          fi
  push-to-registry:
    needs: [bump-version, validate-bump-version-output]
    uses: ./.github/workflows/push-to-registry.yml
    env:
      TAG_NAME: ${{needs.bump-version.outputs.version_number}}
    with:
      tag: $TAG_NAME
    secrets: inherit
