name: Push to ECR Registry

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: tag to use for the image
        default: latest
  pull_request:
    branches: [ master ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      INPUT_PATH: "."
    steps:
    - uses: actions/checkout@v2
    - name: Set default tag
      description: Use 'latest' as default tag
      id: default_tag
      run: |
        default_tag=latest
        echo "::set-output name=default_tag::$default_tag"
    - name: Get short SHA
      id: sha
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
    - name: Get tag
      description: determine whether to use tag from inputs the default tag
      id: tag
      run: |
        input_tag=${{ github.event.inputs.tag }}
        default_tag=${{ steps.default_tag.outputs.default_tag }}
        if [ -z "$input_tag" ]; then
          echo "::set-output name=tag::$default_tag"
        else
          echo "::set-output name=tag::$input_tag"
        fi
    - uses: docker://ghcr.io/kciter/aws-ecr-action:latest
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: rmsd-v2
        region: us-west-1
        tags: ${{ steps.tag.outputs.tag }},${{ steps.sha.outputs.sha7 }}
        dockerfile: docker/Dockerfile
        image_scanning_configuration: true
