name: Push to ECR Registry

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: tag to use for the image
        default: latest
  pull_request:
    branches: [ master ]
    inputs:
      tag:
        type: string
        description: tag to use for the image
        default: latest
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      INPUT_PATH: "."
    steps:
    - uses: actions/checkout@v2
    - name: Get short SHA
      id: sha
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
    - uses: docker://ghcr.io/kciter/aws-ecr-action:latest
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: rmsd-v2
        region: us-west-1
        tags: ${{ github.event.inputs.tag }},${{ steps.sha.outputs.sha7 }}
        dockerfile: docker/Dockerfile
        image_scanning_configuration: true
