name: Push to ECR Registry

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: tag to use for the image
        default: latest
    push:
      tags-ignore:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      INPUT_PATH: "."
      INPUT_EXTRA_BUILD_ARGS: "--target=production"
    steps:
    - uses: actions/checkout@v2
      - ref: "${GITHUB_REF}"  # "${GITHUB_REF##*/}"
    - name: Get repo name
      id: repoName
      run: |
        prefix=nanome-ai/plugin-
        git_repository="${{github.repository}}"
        repo_name=${git_repository/#$prefix} 
        echo $repo_name
        echo "::set-output name=repo_name::$(echo $repo_name)"
    - name: Set default tag
      id: default_tag
      run: |
        default_tag="${GITHUB_REF##*/}"
        echo Default tag = $default_tag
        echo "::set-output name=default_tag::$default_tag"
    - name: Get short SHA
      id: sha
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
    - name: Get tag
      id: tag
      run: |
        input_tag=${{ github.event.inputs.tag }}
        default_tag=${{ steps.default_tag.outputs.default_tag }}
        if [ -z "$input_tag" ]; then
          echo "::set-output name=tag::$default_tag"
        else
          echo "::set-output name=tag::$input_tag"
        fi
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build and Push to ECR public
      id: build-and-push
      uses: pahud/ecr-public-action@8cd826db40befb59b0cd0b60b22a7ba72d06a7f7
      with:
        dockerfile: docker/Dockerfile
        context: . --target production
        tags: |
          public.ecr.aws/h7r1e4h2/${{ steps.repoName.outputs.repo_name }}:${{ steps.tag.outputs.tag }}
