name: Tag latest.
on:
  push:
    branches: [github-actions]

env:
  TAG_NAME: test-latest

jobs:
  tag-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.NANOME_BOT_PAT }}
    - name: git setup
      run: |
        git config --global user.name 'nanome-bot'
        git config --global user.email '45469149+nanome-bot@users.noreply.github.com'
    - name: tag latest
      run: |
        git tag -f $TAG_NAME
    - name: push latest
      run:
        git push -f origin --tags
  push-to-registry:
    - needs: tag-latest
    - uses: nanome-ai/plugin-superimpose-proteins/.github/workflows/push-to-registry.yml@github-actions
      with:
        tag: $TAG_NAME
