name: Tag latest.
on:
  push:
    branches: [master]
jobs:
  tag-latest:
    runs-on: ubuntu-latest
    with:
      ref: test-latest
    steps:
    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
