name: Tag latest.
on:
  push:
    branches: [github-actions]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: tag latest
      run: |
        git tag -a test-latest
    - name: push latest
      run:
        git push -f origin --tags
    