name: Unittests
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: pip install -r requirements.txt
    - run: python run_tests.py
